Repository ZcashFoundation/redjubjub, pull requests merged in 2021-04, with the labels that each got.

#74 Add Release Drafter bot
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
Labels: documentation, enhancement

#67 Derive Debug, PartialEq
  src/frost.rs
Labels: frost

#59 Migrate to jubjub 0.6
  Cargo.toml
  src/frost.rs
  src/hash.rs
  src/lib.rs
  src/scalar_mul.rs
  src/signing_key.rs
  src/verification_key.rs
Labels: dependencies

#55 Upgrade rand, rand_core, and rand_chacha together
  Cargo.toml
  tests/batch.rs
Labels: dependencies
